spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/erp_fd_db?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root # 실제 MySQL 사용자 이름으로 변경
    password: root # 실제 MySQL 비밀번호로 변경
  jpa:
    hibernate:
      ddl-auto: update # 개발 단계에서는 'update'로 설정
    show-sql: true # 실행되는 SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 보기 좋게 포맷

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: your-secret-key-that-is-at-least-256-bits # 256비트 이상(32자 이상)의 비밀키