spring:
  application:
    name: erp-mvp
  datasource:
    url: jdbc:mysql://localhost:3308/erp_mvp?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    time-zone: UTC

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springdoc: DEBUG